### PR TITLE
Added placeholder for username and password fields

### PR DESCRIPTION
**Pull request by devRawnie**
Added placeholder for username and password fields as mentioned in the issue in Login.js and Register.js components

### CODE REVIEW

**Comment by devRawnie** [comment]
For issue no #88

**Review by fave77 — CHANGES_REQUESTED** [review]
@devRawnie please do the same for `Fullname` and `Email` as well in case of `/register`

- John Doe
- johndoe@xyz.com

**Review by fave77 — CHANGES_REQUESTED** [review]
@devRawnie please limit the changes to your PR only!

**Comment by devRawnie** [comment]
@fave77 Could you please explain what do you mean by "Limiting changes to my PR". I don't understand. When I merged remote changes into my repository and tried to push the same to my local repository it asked me to pull from the local repository. I did not understand that but I did it nevertheless. If you could please guide me here, that'd be great.

**Comment by apurv-1** [comment]
> @fave77 Could you please explain what do you mean by "Limiting changes to my PR". I don't understand. When I merged remote changes into my repository and tried to push the same to my local repository it asked me to pull from the local repository. I did not understand that but I did it nevertheless. If you could please guide me here, that'd be great.

It means, do the suggested improvements in the same branch then commit and push the changes, PR will be updated automatically.

**Comment by devRawnie** [comment]
That is what I did. I created the changes in the branch that I created locally. I could repeat the whole process with forking the repository again and creating a new pull request all together.

**Comment by apurv-1** [comment]
You don't need to do the whole process again.
locally just do `git checkout issue_88`.
update with the suggested changes.
then `git commit` and finally push the changes to the remote repo on github.

**Pull request closed without merging**
