### PR TITLE
Article on chess endgames

### PR DESCRIPTION
**Pull request by ShrutiKhatri826**

### CODE REVIEW

**Review by adi-g15 — COMMENTED** [review]
Closes #49

**Comment by adi-g15** [comment]
Closes #49

**Review by apurv-1 — CHANGES_REQUESTED** [review]
Hey @ShrutiKhatri826, I was checking the contents via a plagiarism checker, the score is 93%.
Could you please use your own sentences because our GPL license covers only the code part not the content and we don't expect you to define these definitions by yourself but alteast you could try to make your own sentences? Otherwise, what's the point of this article, we can just share the link to articles. Try to reduce the plagiarism score to 15%.

You can check the Plagiarism Score [here](https://www.quetext.com/results/750f0f6523dfb240c7d9). Hope you understand the point.

Screenshot (165)

**Comment by ShrutiKhatri826** [comment]
Sure, will try to cover it soon.

**Pull request closed without merging**
