### PR TITLE
Fixed #52: Learn page scaling properly

### LINKED ISSUE #52: Learn page not scaling properly when viewed on mobile screen
**Describe the bug** :bug:
Learn page is not scaling accordingly when viewed on mobile screen. A lot of spacing on right side could be seen when you zoom out.

**To Reproduce** :mag:
1. Go to https://develop--pbchess.netlify.app/learn
2. Inspect the page and click on toggle device toolbar
3. Choose any mobile device, say galaxy s5
4. See the error

**Expected behaviour** :honeybee:
The page should scale out properly occupying full width of screen size available

**Screenshots** :camera:
image

**Desktop (please complete the following information):** :computer:
- Works fine on desktop

**Smartphone (please complete the following information):** :iphone:
 - Device: Galaxy S5
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by Vanshikaa00**
## Description
The learn page was not scaling properly on mobile devices

## Motivation and Context
To improve user experience and have a consistent UI design.

## How Has This Been Tested?
1. Go to learn page
2. Inspect the page and click on toggle device toolbar
3. Choose any mobile device
4. Now, it scales appropriately

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by fave77 — CHANGES_REQUESTED** [review]
@Vanshikaa00 A user should be able to zoom in and zoom out, so your PR doesn't actually fix the issue instead it tries to hide the bug. 

For your reference, the overflow issue is due to the content of the term `Forsyth notation`. Try to fix the issue by only modifying the files of `vocab` component!

**Review by fave77 — CHANGES_REQUESTED** [review]
@Vanshikaa00 Do not modify the `/public/index.html`, fix this issue inside `vocab` component!

<a href="https://ibb.co/G5rtHrW">Screenshot-2021-03-14-at-9-32-59-PM</a>

**Comment by Vanshikaa00** [comment]
@fave77 in "update2" commit the user can now zoom in and zoom out too! And at first I did tried to fix this issue by modifying the component's files but it was not having any effect on the page's width. Since the page is designed to be flexible with all devices it will shrink and grow as you alter the size of your browser

**Comment by fave77** [comment]
> @fave77 in "update2" commit the user can now zoom in and zoom out too! And at first I did tried to fix this issue by modifying the component's files but it was not having any effect on the page's width. Since the page is designed to be flexible with all devices it will shrink and grow as you alter the size of your browser

Have you tried modifying the line which is causing the issue?

**Comment by Vanshikaa00** [comment]
Yes I did ! In vocab.css file in class "Container"  i did made the changes but they were not reflecting on the page

**Comment by fave77** [comment]
@Vanshikaa00 just put spaces around the slashes inside `Terms.json`, like so:
```bash
rnbqkbnr/ pppppppp/ 8/8/8/8/ PPPPPPPP/ RNBQKBNR
```

for the term, Forsyth notation

**Comment by fave77** [comment]
@Vanshikaa00 I also noticed some of the titles are overflowing, can you make the font size relative?
<a href="https://ibb.co/yhNnHX5">Screenshot-2021-03-14-at-9-51-23-PM</a>

**Comment by Vanshikaa00** [comment]
Sure and I made the previous changes too..

**Review by fave77 — APPROVED** [review]
@Vanshikaa00 Nice 👍🏻

**Pull request merged**
