### PR TITLE
Scroll to top feature added

### PR DESCRIPTION
**Pull request by DEEPIKA-SUK**
Issue :  #68
Kindly Review my PR.

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
## Description
Added Scroll to top feature on the "Learn" Page.

## Motivation and Context
Since content on the "Learn" page of the website was more so for the convenience for the user of the website, scroll to the top button should be present, which was earlier not present.
Issue: Scroll to top of the page button #68

## How Has This Been Tested?
As the changes are done inside client so it was tested manually.

## Screenshots (if appropriate):

Screenshot (102)
Animated scroll to top button
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:


- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

**Review by fave77 — CHANGES_REQUESTED** [review]
@DEEPIKA-SUK please do not update `index.html` directly, install the required packages using only npm!

**Comment by DEEPIKA-SUK** [comment]
@fave77 I have removed the earlier changes that I did in index.html file and now I have used npm package for font awesome. Kindly review now.

**Review by fave77 — APPROVED** [review]
@DEEPIKA-SUK I was about to tell that the scroll to top button doesn't disappear on moving to the top of page. Anyway nice job 👍🏻

**Pull request merged**
