### PR TITLE
Created Video Component for displaying lichess TV

### LINKED ISSUE #23: Create a 'videos' component for displaying lichess TV
**Is your feature request related to a problem? Please describe.** :bulb:
N/A

**Describe the solution you'd like** :sparkles:

- Visit [https://lichess.org/developers](https://lichess.org/developers) for how to embed the lichess TV
- Theme should be set to `blue-marble`

**Describe alternatives you've considered** :star2:
N/A

**Additional context** :memo:
N/A

### PR DESCRIPTION
**Pull request by Devenkapoor7303**
Added a Video component for displaying liches TV

### CODE REVIEW

**Review by fave77 — CHANGES_REQUESTED** [review]
@Devenkapoor7303 The PR looks good and meets all the requirements. Please change these few details and will merge it next time:
- place the `videos` folder inside the `components` level and not inside `learn` folder
- rename `videosComponent` to just `videos` on both .js and .css filenames
- Capitalise the `videos` function name to `Videos`
- There was a bug in the function name for Learn component. So, change `NotFound` to `Learn`

**Comment by Devenkapoor7303** [comment]
@fave77 okay i am making these changes and thank u for the help

**Comment by fave77** [comment]
@Devenkapoor7303 also take a look at these and make changes accordingly
[https://app.codacy.com/gh/fave77/pbchess/pullRequest?prid=7072682](https://app.codacy.com/gh/fave77/pbchess/pullRequest?prid=7072682)

P.S. - Use single quotes wherever possible

**Comment by Devenkapoor7303** [comment]
okay i will these changes also @fave77

**Review by fave77 — APPROVED** [review]

**Pull request merged**
