### PR TITLE
feat: Addition of Icons and Navbar Alignment

### LINKED ISSUE #109: Spacial arrangements and adding Icons to the Content in navbar
**Describe the bug** :bug:
Contents in the navbar on the homepage are not arranged spacially 

**Expected behavior** :honeybee:
Space between  Play Learn Login can be increased, The UI design of the navbar can be improved (can include icons for it to look visually pleasing). 

**Screenshots** :camera:
image

### PR DESCRIPTION
**Pull request by anhushree**
The icons were added in the Navbar to improve the Visual experience

image

### CODE REVIEW

**Review by fave77 — CHANGES_REQUESTED** [review]
@anhushree looks great 👍🏻 .... but please do the same for the following as well:
- profile
- change_pswd
- logout

when a user signs in

**Comment by anhushree** [comment]
ok will update it soon

**Comment by anhushree** [comment]
@fave77 I have updated the inside screens as well, can you please test it out as I'll have set up the backend repo for testing which I'm not aware of it. Do let me know if any other changes are to be done. Thank you.

**Review by fave77 — APPROVED** [review]
@anhushree nice job 👍🏻

**Pull request merged**
